- hosts: redpanda
  tasks:

  - name: ensure /etc/redpanda exists
    file:
      path: /etc/redpanda
      state: directory

  - name: configure redpanda
    notify:
      - restart redpanda-tuner
      - restart redpanda
    vars:
      use_public_ips: true
    shell: |
      set -e
      rpk config set cluster_id 'redpanda'
      rpk config set organization 'redpanda-test'
      sudo rpk config set redpanda.advertised_kafka_api '{ address: {{ inventory_hostname }}, port: 9092}' --format yaml
      sudo rpk config set redpanda.advertised_rpc_api '{ address: {{ inventory_hostname }}, port: 33145}' --format yaml
      {% if hostvars[groups['redpanda'][0]].id == hostvars[inventory_hostname].id %}
      sudo rpk config bootstrap \
        --id {{ hostvars[inventory_hostname].id }} \
        --self {{ hostvars[inventory_hostname].private_ip }}
      {% else %}
      sudo rpk config bootstrap \
        --id {{ hostvars[inventory_hostname].id }} \
        --self {{ hostvars[inventory_hostname].private_ip }} \
        --ips {{ groups['redpanda'][0] }}
      {% endif %}
      sudo rpk config set redpanda.enable_transactions false
      sudo rpk config set redpanda.enable_idempotence false
  handlers:
  - name: restart redpanda-tuner
    systemd:
      name: redpanda-tuner
      state: restarted
  - name: restart redpanda
    systemd:
      name: redpanda
      state: restarted